# Generated by Django 4.0.1 on 2022-01-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating_of_stealablitiy', models.CharField(choices=[('zero', 'American President Nuclear Football'), ('one', 'Face off of Mt. Rushmore'), ('two', 'Part of the Daytona Track During a Race'), ('three', 'The Top of the "Effifel" tower in Las Vegas'), ('four', 'Items from Walmart'), ('five', 'Views of the Grand Canyon')], default='five', max_length=5)),
                ('member_of_which_evil_organization', models.CharField(choices=[('aim', 'Advanced Idea Mechanics AIM'), ('cobra', 'Criminal Organization of Bloodiness, Revenge and Assassination COBRA'), ('HYDRA', 'HYDRA'), ('skool', 'Secert Knowledge of Organized Lawbreakers SKOOL'), ('vile', 'The Villians International League of Evil VILE')], max_length=5)),
                ('location', models.CharField(max_length=128)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
