# Generated by Django 4.0.1 on 2022-01-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stealable_landmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='rating_of_stealablitiy',
            new_name='rating_of_stealablity',
        ),
    ]
